import { useSession } from 'next-auth/react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import Dashboard from '../Components/Dashboard'
import Loader from '../Components/Loader'


export default function Home() {
  const router = useRouter()
  const {status, data: session} = useSession({
    required:true,
    onUnauthenticated(){
      router.push('/auth/signin')
    }
  })

  if(status === 'loading') {
    return <Loader />
  }
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dashboard />
    </div>
  )
}
